name: environmental_analysis_model
description: "Model for analyzing indoor environmental data."

tables:
  - name: environmental_data
    description: "Contains time-series data for temperature, humidity, and CO2 levels."
    base_table:
      database: MELIPS_HANDS_ON
      schema: STAGING
      table: ENVIRONMENTAL_DATA
    primary_key:
      columns:
        - locationID
        - timestamp_hour # Composite primary key
    time_dimensions:
      - name: timestamp_hour
        expr: '"service_timestamp_hour"'
        data_type: TIMESTAMP_TZ
    dimensions:
      - name: locationID
        expr: '"locationID"'
        data_type: NUMBER
    facts:
      - name: temperature
        expr: '"TEMPERATURE"'
        data_type: NUMBER
      - name: humidity
        expr: '"HUMIDITY"'
        data_type: NUMBER
      - name: co2
        expr: '"CO2"'
        data_type: NUMBER

  - name: room_info
    description: "Contains information about each room or location."
    base_table:
      database: MELIPS_HANDS_ON
      schema: STAGING
      table: ROOM_INFO
    primary_key:
      columns:
        - locationID
    dimensions:
      - name: locationID
        expr: '"locationID"'
        data_type: NUMBER
      - name: areaCategory
        expr: '"areaCategory"'
        data_type: TEXT
      - name: areaSize
        expr: '"AreaSize"'
        data_type: NUMBER

metrics:
  - name: avg_temperature
    expr: "AVG(environmental_data.temperature)"
  - name: avg_humidity
    expr: "AVG(environmental_data.humidity)"
  - name: avg_co2
    expr: "AVG(environmental_data.co2)"
  - name: record_count
    expr: "COUNT(*)"

relationships:
  - name: env_data_to_room_info
    left_table: environmental_data
    right_table: room_info
    relationship_columns:
      - left_column: locationID
        right_column: locationID
    join_type: left_outer
    relationship_type: many_to_one
